import { motion, useScroll, useTransform } from 'framer-motion';
import { useRef } from 'react';
import Layout from '../../components/Layout';
import { ArrowRight, Music, Wand2, ImageIcon, Sparkles } from 'lucide-react';

const Home = () => {
  const ref = useRef(null);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ['start start', 'end start'],
  });

  const yBg = useTransform(scrollYProgress, [0, 1], ['0%', '50%']);
  const opacityBg = useTransform(scrollYProgress, [0, 0.5], [1, 0]);

  const features = [
    {
      icon: <Wand2 className='w-8 h-8 text-spotify-brand' />,
      title: 'AI-Powered Playlists',
      description:
        'Our advanced AI analyzes your prompts to create perfectly tailored playlists that match your mood, activity, or any concept you imagine.',
    },
    {
      icon: <ImageIcon className='w-8 h-8 text-spotify-brand' />,
      title: 'Automated Cover Art',
      description:
        'Every generated playlist comes with unique AI-created cover art based on your keywords, making your playlists visually distinctive.',
    },
    {
      icon: <Sparkles className='w-8 h-8 text-spotify-brand' />,
      title: 'Smart Personalization',
      description:
        'The more you use it, the better it gets at understanding your musical taste and preferences.',
    },
  ];

  return (
    <Layout>
      {/* Hero Section with Parallax Effect */}
      <section
        ref={ref}
        className='relative h-screen w-full overflow-hidden flex items-center justify-center'
      >
        <motion.div
          style={{ y: yBg, opacity: opacityBg }}
          className='absolute inset-0 bg-gradient-to-b from-spotify-gray-900 to-spotify-black z-0'
        />

        <div className="absolute inset-0 bg-[url('/images/music-pattern.png')] opacity-5 z-0" />

        <div className='relative z-10 max-w-7xl mx-auto px-6 text-center'>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className='mb-8'
          >
            <span className='inline-flex items-center gap-2 bg-spotify-gray-800 text-spotify-brand px-4 py-2 rounded-full text-sm font-medium'>
              <Music className='w-4 h-4' /> AI Music Revolution
            </span>
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className='text-5xl md:text-7xl font-bold text-spotify-white mb-6'
          >
            Your <span className='text-spotify-brand'>Perfect Playlist</span>
            <br />
            Generated by AI
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.4 }}
            className='text-xl text-spotify-gray-400 max-w-3xl mx-auto mb-10'
          >
            Describe your mood, activity, or music preference, and our AI will
            create a personalized Spotify playlist with matching cover art -
            automatically.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.6 }}
            className='flex flex-col sm:flex-row gap-4 justify-center'
          >
            <a
              href='/playlist-gen'
              className='bg-spotify-brand hover:bg-spotify-green-light text-spotify-black font-bold rounded-full px-8 py-4 flex items-center gap-2 transition-all duration-200 hover:scale-105'
            >
              Try Playlist Gen <ArrowRight className='w-5 h-5' />
            </a>
            <a
              href='#how-it-works'
              className='border border-spotify-gray-600 hover:border-spotify-white text-spotify-white font-bold rounded-full px-8 py-4 flex items-center gap-2 transition-all duration-200'
            >
              Learn More
            </a>
          </motion.div>
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1, delay: 1 }}
          className='absolute bottom-10 left-1/2 transform -translate-x-1/2'
        >
          <div className='animate-bounce w-8 h-8 border-4 border-spotify-gray-400 rounded-full'></div>
        </motion.div>
      </section>

      {/* How It Works Section */}
      <section id='how-it-works' className='py-20 bg-spotify-black'>
        <div className='max-w-7xl mx-auto px-6'>
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true, margin: '-100px' }}
            transition={{ duration: 0.8 }}
            className='text-center mb-16'
          >
            <h2 className='text-3xl md:text-4xl font-bold text-spotify-white mb-4'>
              How It Works
            </h2>
            <p className='text-spotify-gray-400 max-w-2xl mx-auto'>
              Transforming your ideas into perfect playlists has never been
              easier. Just follow these simple steps.
            </p>
          </motion.div>

          <div className='grid md:grid-cols-3 gap-8'>
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 50 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: '-100px' }}
                transition={{ duration: 0.5, delay: index * 0.2 }}
                className='bg-spotify-gray-900 rounded-xl p-8 hover:bg-spotify-gray-800 transition-colors duration-300'
              >
                <div className='mb-6'>{feature.icon}</div>
                <h3 className='text-xl font-bold text-spotify-white mb-3'>
                  {feature.title}
                </h3>
                <p className='text-spotify-gray-400'>{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Authentication Notice */}
      <section className='py-20 bg-gradient-to-b from-spotify-gray-900 to-spotify-black'>
        <div className='max-w-4xl mx-auto px-6 text-center'>
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className='bg-spotify-gray-900 rounded-xl p-8 md:p-12 border border-spotify-gray-700'
          >
            <h2 className='text-2xl md:text-3xl font-bold text-spotify-white mb-6'>
              Important Notice About Spotify Authentication
            </h2>
            <p className='text-spotify-gray-400 mb-8'>
              This application is{' '}
              <span className='text-spotify-white font-medium'>
                not affiliated with Spotify
              </span>{' '}
              in any way. We use Spotify's official API to create playlists on
              your behalf, which requires you to authenticate with your Spotify
              account. This ensures your playlists are saved directly to your
              Spotify library.
            </p>
            <p className='text-spotify-gray-300 text-sm'>
              By authenticating, you grant us permission to create playlists in
              your Spotify account. We don't store your credentials and only
              request the minimum permissions needed.
            </p>
          </motion.div>
        </div>
      </section>

      {/* CTA Section */}
      <section className='py-20 bg-spotify-black'>
        <div className='max-w-4xl mx-auto px-6 text-center'>
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
          >
            <h2 className='text-3xl md:text-4xl font-bold text-spotify-white mb-6'>
              Ready to Experience AI-Powered Playlists?
            </h2>
            <p className='text-spotify-gray-400 mb-8 max-w-2xl mx-auto'>
              Join thousands of users who are discovering their perfect
              soundtracks with just a few words.
            </p>
            <a
              href='/playlist-gen'
              className='inline-block bg-spotify-brand hover:bg-spotify-green-light text-spotify-black font-bold rounded-full px-8 py-4 flex items-center gap-2 transition-all duration-200 hover:scale-105 mx-auto w-fit'
            >
              Start Creating Now <ArrowRight className='w-5 h-5' />
            </a>
          </motion.div>
        </div>
      </section>
    </Layout>
  );
};

export default Home;
